name:每日日志检查
on:
schedule:
- cron: '30 5 * * *'  #每天早上5.30自动运行
jobs:
check:
runs-on:ubuntu-latest
steps:
- uses:actions/checkout@v4
- name:检查日志
run: |
if [ ! -f "DAILY_LOG/$(date -d '-1 day' +%Y-%m-%d).md" ]; then
echo "昨天没写日志！" >> $GITHUB_STEP_SUMMARY
exit 1
fi
